### ISSUE TITLE
Node.js port

### ISSUE THREAD

**Issue by jbrooksuk** [selvinortiz/flux#1]
@selvinortiz, I've written a Node.js port of flux which you can install from the [NPM registry here](https://npmjs.org/package/node-flux). Function names are the same, it's almost a straight port, only a few changes for using `new RegExp`, the tests pass though.

I'll try and keep the port up to date with this repository and update the README later.

**Comment by alexanderbartels** [comment]
@selvinortiz, I've written a port of flux, too. It is written in golang.

I've started to learn golang and i needed some Regex for a small project, so i've started to port your project.

Thanks for your work! :-)

**Comment by selvinortiz** [comment]
@alexanderbartels Nice man, I've been meaning to read up on **go** for a while and have only done so briefly but haven't written anything in it yet. Your implementation looks nice!
