### ISSUE TITLE
Zero sized ranges don't create valid patterns

### ISSUE THREAD

**Issue by roxburghm** [selvinortiz/flux#11]
Hi,

Thanks for lib, great. Slight issue

->letters(0,1)

creates a pattern

[a-zA-Z]+

rather than 

[a-zA-Z]{0,1}

Fix is to compare to null rather than if ($min) which fails if ZERO provided.

Same in all other functions where min and max allowed.

Matt

	public function letters($min = null, $max = null)
	{

		if (!is_null($min) && !is_null($max))
		{
			return $this->raw(sprintf('([a-zA-Z]{%d,%d})', $min, $max));
		}
		elseif (!is_null($min) && is_null($max))
		{
			return $this->raw(sprintf('([a-zA-Z]{%d})', $min));
		}
		else
		{
			return $this->raw('([a-zA-Z]+)');
		}
	}

**Comment by selvinortiz** [comment]
Thanks for the heads up and your solution @roxburghm, I'll try to get the update in place soon.

Happy to merge in a pull request though;)

**Comment by roxburghm** [comment]
No problem, I'll sort out a pull request fit you and do the changes

**Comment by roxburghm** [comment]
Fixed
