### ISSUE TITLE
Maybe letters or digits

### ISSUE THREAD

**Issue by apburton84** [selvinortiz/flux#13]
Is there currently functionality for this type of regular expression:

    ([A-Z]+)? 

Something like:

    $flux->maybe($flux->letters());

or 

    $flux->maybeLetters();

Any help in this regard would be greatly appreciated

**Comment by selvinortiz** [comment]
@apburton84 There is a method for each of those starting at line (488) https://github.com/selvinortiz/flux/blob/master/src/SelvinOrtiz/Utils/Flux/Flux.php#L488

If those (`letters/digits`) don't behave as expected, please let me know and I can revise.

**Comment by apburton84** [comment]
I see, so its a case of:

   $flux->digits(0, n);

Thank you
