### ISSUE TITLE
digits 0 or more

### ISSUE THREAD

**Issue by apburton84** [selvinortiz/flux#14]
I would like to find 0 or more digits, like so:

    $flux->digits(0, 10);

however, the digits method will always fall to the else, as 0 is false and the condition states $min && $max see below:

    if ($min && $max)
    {
        return $this->raw(sprintf('(\\d{%d,%d})', $min, $max));
    }

I may be misunderstanding how to achieve the 0 or more with the Flux library. However 

    if (! is_null($min) && ! is_null($max))

Would resolve the issue for my use case. What would you thoughts be on this?

**Comment by apburton84** [comment]
The same is true of:

    $flux->letters(0, 10);

**Comment by apburton84** [comment]
I see this has been resolved

52948d0

Switched composer to use dev-master for the time being, any timescale on the release on 0.5.3 ?

**Comment by selvinortiz** [comment]
@apburton84 I'll be getting it merge with master and cutting a new release very shortly. Sorry for my delayed response, been a pretty busy month so far:)
