### ISSUE TITLE
Consider droppping php-5.x supports

### ISSUE THREAD

**Issue by peter279k** [selvinortiz/flux#16]
Since PHP `7.1` version is released and it's current PHP version.

I think this should be considered.

Once this issue is accepted, I would be happy to this :).

**Comment by selvinortiz** [comment]
Go for it!

**Comment by bcalik** [comment]
You don't need to drop if it doesn't block the development in someway.

**Comment by peter279k** [comment]
We can release new version to support only `php-7.2` versions.

And it's nice to split two versions to do backward compatibility.
